### ISSUE TITLE
使用WebRTC无法正常推流

### ISSUE THREAD

**Issue by BySlin** [Monibuca/plugin-webrtc#21]
```typescript
    const mediaStream = await navigator.mediaDevices.getUserMedia({
      video: true,
      audio: true,
    });
    refVideo.current!.srcObject = mediaStream;
    setMediaStream(mediaStream);
    const pc = new RTCPeerConnection();
    pc.addTransceiver('video', { direction: 'sendonly' });
    pc.addTransceiver('audio', { direction: 'sendonly' });
    pc.oniceconnectionstatechange = () => {
      console.log('oniceconnectionstatechange', pc.iceConnectionState);
    };
    pc.onicecandidate = (e) => {
      console.log('onicecandidate', e.candidate);
    };
    mediaStream.getTracks().forEach((t) => {
      pc.addTrack(t, mediaStream);
    });
    const offer = await pc.createOffer();
    await pc.setLocalDescription(offer);
    const result = await fetch(
      `http://127.0.0.1:8080/webrtc/push/live/webrtc11`,
      {
        method: 'POST',
        mode: 'cors',
        cache: 'no-cache',
        credentials: 'include',
        redirect: 'follow',
        referrerPolicy: 'no-referrer',
        headers: { 'Content-Type': 'application/sdp' },
        body: offer.sdp,
      },
    );
    const remoteSdp = await result.text();
    await pc.setRemoteDescription(
      new RTCSessionDescription({ type: 'answer', sdp: remoteSdp }),
    );
    setPc(pc);

```

使用如上代码，无法进行webrtc推流

<img width="855" alt="微信截图_20230220213823" src="https://user-images.githubusercontent.com/16970823/220123559-d912573c-af40-4d06-bac0-a5ef037ec92f.png">

**Comment by langhuihui** [comment]
我来修复一下

**Comment by langhuihui** [comment]
你再试试，已经发版了

**Comment by BySlin** [comment]
是可以正常推了，但是程序会闪退
<img width="865" alt="image" src="https://user-images.githubusercontent.com/16970823/220225042-84ea9936-6868-4702-894f-ab37bf67faad.png">

**Comment by langhuihui** [comment]
你也可以帮我排查一下

**Comment by BySlin** [comment]
我就成功推流一次，后面就没成功过了，每次都闪退，版本是最新的4.4.7，直接解压，啥配置都没改，日志如下，走到最后一句就闪退了，
```
10:24:26	[33mWARN[0m	origin config error plugin disabled	{"plugin": "Edge"}
10:24:26	[34mINFO[0m	webrtc start listen	{"plugin": "WebRTC", "port": 9000}
10:24:26	[33mWARN[0m	no cert or key file specified, plugin disabled	{"plugin": "WebTransport"}
10:24:26	[34mINFO[0m	[32mServer gb28181 start at[0m [94m0.0.0.0:5060[0m	{"plugin": "GB28181"}
10:24:26	[34mINFO[0m	Media udp server start.	{"plugin": "GB28181", "port": 58200}
10:24:26	[34mINFO[0m	server rtmp start at	{"plugin": "RTMP", "listen addr": ":1935"}
10:24:26	[34mINFO[0m	[5mm7s@v4.4.7[0m start success
10:24:27	[34mINFO[0m	LocalAndInternalIPs detail: map[171.43.147:171.43.147.42 171.43.147.42:171.43.147.42 192.168.31:192.168.31.20 192.168.31.20:171.43.147.42]	{"plugin": "GB28181"}
10:24:28	[34mINFO[0m	publish	{"plugin": "WebRTC", "path": "live/webrtc11"}
10:24:28	[34mINFO[0m	created	{"stream": "live/webrtc11"}
10:24:28	[34mINFO[0m	⌛[33m->[0m🟢	{"stream": "live/webrtc11", "action": "publish"}
10:24:28	[34mINFO[0m	subscribe	{"plugin": "HLS", "path": "live/webrtc11"}
10:24:28	[34mINFO[0m	innersuber +1	{"stream": "live/webrtc11", "type": "HLSWriter", "remains": 1}
10:24:28	[34mINFO[0m	Connection State has changed:checking	{"stream": "live/webrtc11", "type": "WebRTCPublisher"}
10:24:28	[34mINFO[0m	candidate:1800218024 1 udp 2130706431 192.168.31.20 9000 typ host	{"stream": "live/webrtc11", "type": "WebRTCPublisher"}
10:24:28	[34mINFO[0m	candidate:2878742611 1 udp 2130706431 127.0.0.1 9000 typ host	{"stream": "live/webrtc11", "type": "WebRTCPublisher"}
10:24:28	[34mINFO[0m	Connection State has changed:connected	{"stream": "live/webrtc11", "type": "WebRTCPublisher"}
10:24:28	[34mINFO[0m	audio track attached	{"stream": "live/webrtc11", "track": "pcmu", "sample rate": 8000}
10:24:29	[34mINFO[0m	video track attached	{"stream": "live/webrtc11", "track": "h264", "width": 320, "height": 240}
10:24:29	[34mINFO[0m	track+1	{"stream": "live/webrtc11", "type": "HLSWriter", "name": "h264"}
10:24:29	[34mINFO[0m	playblock	{"stream": "live/webrtc11", "type": "HLSWriter"}
10:24:29	[34mINFO[0m	start read	{"stream": "live/webrtc11", "type": "HLSWriter", "track": "h264", "mode": 0}
10:24:29	[34mINFO[0m	first frame read	{"stream": "live/webrtc11", "type": "HLSWriter", "track": "h264", "firstTs": 0, "firstSeq": 0}

```

fatal.log
```
--------------------------------
panic: runtime error: index out of range [0] with length 0

goroutine 141 [running]:
m7s.live/engine/v4/common.(*RTPFrame).H264Type(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.11.7/common/frame.go:32
m7s.live/engine/v4/track.(*H264).WriteRTPFrame(0x7c85006600010102, 0x9e801351ae8f4617)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.11.7/track/h264.go:104 +0x497
m7s.live/engine/v4/track.(*Media).writeRTPFrame(0xc000198000, 0xc000c1e000)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.11.7/track/rtp.go:37 +0xd6
m7s.live/engine/v4/track.(*Media).WriteRTP(0xc000198000, {0xc0011e9800?, 0x5b4?, 0x5b4?})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.11.7/track/rtp.go:58 +0x3c
m7s.live/plugin/webrtc/v4.(*WebRTCPublisher).OnEvent.func2(0xc0011a2000, 0xc0011180b0?)
	/home/runner/go/pkg/mod/m7s.live/plugin/webrtc/v4@v4.0.6/publisher.go:69 +0x311
created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
	/home/runner/go/pkg/mod/github.com/pion/webrtc/v3@v3.1.49/peerconnection.go:462 +0x178

```


```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>测试WebRTC推流</title>
</head>

<body>
    <video id="video" width="600" height="600" autoplay muted />
</body>
<script>
    (async () => {
        const mediaStream = await navigator.mediaDevices.getUserMedia({
            video: true,
            audio: true,
        });
        document.getElementById('video').srcObject = mediaStream;
        const pc = new RTCPeerConnection();
        pc.addTransceiver('video', { direction: 'sendonly' });
        pc.addTransceiver('audio', { direction: 'sendonly' });
        pc.oniceconnectionstatechange = () => {
            console.log('oniceconnectionstatechange', pc.iceConnectionState);
        };
        pc.onicecandidate = (e) => {
            console.log('onicecandidate', e.candidate);
        };
        mediaStream.getTracks().forEach((t) => {
            pc.addTrack(t, mediaStream);
        });
        const offer = await pc.createOffer();
        await pc.setLocalDescription(offer);
        const result = await fetch(
            `http://127.0.0.1:8080/webrtc/push/live/webrtc11`,
            {
                method: 'POST',
                mode: 'cors',
                cache: 'no-cache',
                credentials: 'include',
                redirect: 'follow',
                referrerPolicy: 'no-referrer',
                headers: { 'Content-Type': 'application/sdp' },
                body: offer.sdp,
            },
        );
        const remoteSdp = await result.text();
        await pc.setRemoteDescription(
            new RTCSessionDescription({ type: 'answer', sdp: remoteSdp }),
        );
    })()
</script>

</html>
```

**Comment by langhuihui** [comment]
找到原因了，有空的rtp包引起的，我加个过滤就行了

**Comment by BySlin** [comment]
4.4.8已修复
